repos:

  # Standard Python Files
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - "types-requests"
          - "types-tabulate"
          - "types-PyYAML"
          - "types-cachetools"

  # Notebooks
  # - repo: https://github.com/nbQA-dev/nbQA
  #   rev: 1.9.1
  #   hooks:
  #     - id: nbqa-black
  #     - id: nbqa-ruff
  #       args: ["--fix"]